apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: blendnet-cms-api
spec:
  replicas: 1
  template:
    metadata:
      labels:
        service: site
    spec:
      containers:
      - name: aspnetapp
        image: mcr.microsoft.com/dotnet/samples:aspnetapp
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          periodSeconds: 3
          timeoutSeconds: 1
